name: Deploy Storybook to GitHub Pages

on:
  # Executa a action toda vez que fizer um push na branch main (pode mudar se sua principal for 'master')
  push:
    branches: [ "main" ]

  # Permite rodar manualmente pela interface do GitHub
  workflow_dispatch:

# Permissões necessárias para modificar os arquivos gerados no git para o GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          force_orphan: true
